services:
  ssh-jumphost:
    image: git.debilux.org/chris/nsupdate
    container_name: ssh-jumphost
    restart: unless-stopped
    volumes:
      - ./config:/config
    ports:
      - 2222:2222
    tmpfs:
      - /tmp
      - /run
      - /var/tmp
    read_only: true